// TOP CUSTOMERSLIST OPERATION(Read)
export const TOP_TEN_3KG_CUSTOMERS_REQUEST = 'TOP_TEN_3KG_CUSTOMERS_REQUEST';
export const TOP_TEN_3KG_CUSTOMERS_SUCCESS = 'TOP_TEN_3KG_CUSTOMERS_SUCCESS';
export const TOP_TEN_3KG_CUSTOMERS_FAIL = 'TOP_TEN_3KG_CUSTOMERS_FAIL';
//for 6kg
export const TOP_TEN_6KG_CUSTOMERS_REQUEST = 'TOP_TEN_6KG_CUSTOMERS_REQUEST';
export const TOP_TEN_6KG_CUSTOMERS_SUCCESS = 'TOP_TEN_6KG_CUSTOMERS_SUCCESS';
export const TOP_TEN_6KG_CUSTOMERS_FAIL = 'TOP_TEN_6KG_CUSTOMERS_FAIL';
//for13kg
export const TOP_TEN_13KG_CUSTOMERS_REQUEST = 'TOP_TEN_13KG_CUSTOMERS_REQUEST';
export const TOP_TEN_13KG_CUSTOMERS_SUCCESS = 'TOP_TEN_13KG_CUSTOMERS_SUCCESS';
export const TOP_TEN_13KG_CUSTOMERS_FAIL = 'TOP_TEN_13KG_CUSTOMERS_FAIL';
//for 25kg
export const TOP_TEN_25KG_CUSTOMERS_REQUEST = 'TOP_TEN_25KG_CUSTOMERS_REQUEST';
export const TOP_TEN_25KG_CUSTOMERS_SUCCESS = 'TOP_TEN_25KG_CUSTOMERS_SUCCESS';
export const TOP_TEN_25KG_CUSTOMERS_FAIL = 'TOP_TEN_CUSTOMERS_FAIL';
//for 35kg
export const TOP_TEN_35KG_CUSTOMERS_REQUEST = 'TOP_TEN_35KG_CUSTOMERS_REQUEST';
export const TOP_TEN_35KG_CUSTOMERS_SUCCESS = 'TOP_TEN_35KG_CUSTOMERS_SUCCESS';
export const TOP_TEN_35KG_CUSTOMERS_FAIL = 'TOP_TEN_35KG_CUSTOMERS_FAIL';
//for 50kg
export const TOP_TEN_50KG_CUSTOMERS_REQUEST = 'TOP_TEN_50KG_CUSTOMERS_REQUEST';
export const TOP_TEN_50KG_CUSTOMERS_SUCCESS = 'TOP_TEN_50KG_CUSTOMERS_SUCCESS';
export const TOP_TEN_50KG_CUSTOMERS_FAIL = 'TOP_TEN_50KG_CUSTOMERS_FAIL';

//LIST OPERATION(Read)
export const TOP_SOLD_GAS_REQUEST = 'TOP_SOLD_GAS_REQUEST';
export const TOP_SOLD_GAS_SUCCESS = 'TOP_SOLD_GAS_SUCCESS';
export const TOP_SOLD_GAS_FAIL = 'TOP_SOLD_GAS_FAIL';

//LIST OPERATION(Read)
export const GAS_FOR_3KG_REFILL_REQUEST = 'GAS_FOR_3KG_REFILL_REQUEST';
export const GAS_FOR_3KG_REFILL_SUCCESS = 'GAS_FOR_3KG_REFILL_SUCCESS';
export const GAS_FOR_3KG_REFILL_FAIL = 'GAS_FOR_3KG_REFILL_FAIL';

export const GAS_FOR_6KG_REFILL_REQUEST = 'GAS_FOR_6KG_REFILL_REQUEST';
export const GAS_FOR_6KG_REFILL_SUCCESS = 'GAS_FOR_6KG_REFILL_SUCCESS';
export const GAS_FOR_6KG_REFILL_FAIL = 'GAS_FOR_6KG_REFILL_FAIL';

export const GAS_FOR_13KG_REFILL_REQUEST = 'GAS_FOR_13KG_REFILL_REQUEST';
export const GAS_FOR_13KG_REFILL_SUCCESS = 'GAS_FOR_13KG_REFILL_SUCCESS';
export const GAS_FOR_13KG_REFILL_FAIL = 'GAS_FOR_13KG_REFILL_FAIL';

export const GAS_FOR_25KG_REFILL_REQUEST = 'GAS_FOR_25KG_REFILL_REQUEST';
export const GAS_FOR_25KG_REFILL_SUCCESS = 'GAS_FOR_25KG_REFILL_SUCCESS';
export const GAS_FOR_25KG_REFILL_FAIL = 'GAS_FOR_25KG_REFILL_FAIL';

export const GAS_FOR_35KG_REFILL_REQUEST = 'GAS_FOR_35KG_REFILL_REQUEST';
export const GAS_FOR_35KG_REFILL_SUCCESS = 'GAS_FOR_35KG_REFILL_SUCCESS';
export const GAS_FOR_35KG_REFILL_FAIL = 'GAS_FOR_35KG_REFILL_FAIL';

export const GAS_FOR_50KG_REFILL_REQUEST = 'GAS_FOR_50KG_REFILL_REQUEST';
export const GAS_FOR_50KG_REFILL_SUCCESS = 'GAS_FOR_50KG_REFILL_SUCCESS';
export const GAS_FOR_50KG_REFILL_FAIL = 'GAS_FOR_50KG_REFILL_FAIL';

//LIST OPERATION(Read)
export const GAS_3KG_MONTH_REVENUE_REQUEST = 'GAS_3KG_MONTH_REVENUE_REQUEST';
export const GAS_3KG_MONTH_REVENUE_SUCCESS = 'GAS_3KG_MONTH_REVENUE_SUCCESS';
export const GAS_3KG_MONTH_REVENUE_FAIL = 'GAS_3KG_MONTH_REVENUE_FAIL';

export const GAS_6KG_MONTH_REVENUE_REQUEST = 'GAS_6KG_MONTH_REVENUE_REQUEST';
export const GAS_6KG_MONTH_REVENUE_SUCCESS = 'GAS_6KG_MONTH_REVENUE_SUCCESS';
export const GAS_6KG_MONTH_REVENUE_FAIL = 'GAS_6KG_MONTH_REVENUE_FAIL';

export const GAS_13KG_MONTH_REVENUE_REQUEST = 'GAS_13KG_MONTH_REVENUE_REQUEST';
export const GAS_13KG_MONTH_REVENUE_SUCCESS = 'GAS_13KG_MONTH_REVENUE_SUCCESS';
export const GAS_13KG_MONTH_REVENUE_FAIL = 'GAS_13KG_MONTH_REVENUE_FAIL';

export const GAS_25KG_MONTH_REVENUE_REQUEST = 'GAS_25KG_MONTH_REVENUE_REQUEST';
export const GAS_25KG_MONTH_REVENUE_SUCCESS = 'GAS_25KG_MONTH_REVENUE_SUCCESS';
export const GAS_25KG_MONTH_REVENUE_FAIL = 'GAS_25KG_MONTH_REVENUE_FAIL';

export const GAS_35KG_MONTH_REVENUE_REQUEST = 'GAS_35KG_MONTH_REVENUE_REQUEST';
export const GAS_35KG_MONTH_REVENUE_SUCCESS = 'GAS_35KG_MONTH_REVENUE_SUCCESS';
export const GAS_35KG_MONTH_REVENUE_FAIL = 'GAS_35KG_MONTH_REVENUE_FAIL';

export const GAS_50KG_MONTH_REVENUE_REQUEST = 'GAS_50KG_MONTH_REVENUE_REQUEST';
export const GAS_50KG_MONTH_REVENUE_SUCCESS = 'GAS_50KG_MONTH_REVENUE_SUCCESS';
export const GAS_50KG_MONTH_REVENUE_FAIL = 'GAS_50KG_MONTH_REVENUE_FAIL';
