//CREATE CUSTOMER ORDER OPERATION)(Create)
export const CUSTOMER_ORDER_CREATE_REQUEST = 'CUSTOMER_ORDER_CREATE_REQUEST';
export const CUSTOMER_ORDER_CREATE_SUCCESS = 'CUSTOMER_ORDER_CREATE_SUCCESS';
export const CUSTOMER_ORDER_CREATE_FAIL = 'CUSTOMER_ORDER_CREATE_FAIL';
export const CUSTOMER_ORDER_CREATE_RESET = 'CUSTOMER_ORDER_CREATE_RESET';

//READ CUSTOMER ORDER OPERATION(Read-LIST)
export const CUSTOMER_ORDER_LIST_REQUEST = 'CUSTOMER_ORDER_LIST_REQUEST';
export const CUSTOMER_ORDER_LIST_SUCCESS = 'CUSTOMER_ORDER_LIST_SUCCESS';
export const CUSTOMER_ORDER_LIST_FAIL = 'CUSTOMER_ORDER_LIST_FAIL';

//READ CUSTOMER ORDER OPERATION(Read-DETAILS)
export const CUSTOMER_ORDER_DETAILS_REQUEST = 'CUSTOMER_ORDER_DETAILS_REQUEST';
export const CUSTOMER_ORDER_DETAILS_SUCCESS = 'CUSTOMER_ORDER_DETAILS_SUCCESS';
export const CUSTOMER_ORDER_DETAILS_FAIL = 'CUSTOMER_ORDER_DETAILS_FAIL';

//DELETE CUSTOMER ORDER OPERATION(Update)
export const CUSTOMER_ORDER_UPDATE_REQUEST = 'CUSTOMER_ORDER_UPDATE_REQUEST';
export const CUSTOMER_ORDER_UPDATE_SUCCESS = 'CUSTOMER_ORDER_UPDATE_SUCCESS';
export const CUSTOMER_ORDER_UPDATE_FAIL = 'CUSTOMER_ORDER_UPDATE_FAIL';
export const CUSTOMER_ORDER_UPDATE_RESET = 'CUSTOMER_ORDER_UPDATE_RESET';

//UPDATE CUSTOMER ORDER OPERATION(Update)
export const CUSTOMER_ORDER_DELIVER_REQUEST = 'CUSTOMER_ORDER_DELIVER_REQUEST';
export const CUSTOMER_ORDER_DELIVER_SUCCESS = 'CUSTOMER_ORDER_DELIVER_SUCCESS';
export const CUSTOMER_ORDER_DELIVER_FAIL = 'CUSTOMER_ORDER_DELIVER_FAIL';
export const CUSTOMER_ORDER_DELIVER_RESET = 'CUSTOMER_ORDER_DELIVER_RESET';

//UPDATE CUSTOMER ORDER OPERATION(Update)
export const CUSTOMER_ORDER_PAID_REQUEST = 'CUSTOMER_ORDER_PAID_REQUEST';
export const CUSTOMER_ORDER_PAID_SUCCESS = 'CUSTOMER_ORDER_PAID_SUCCESS';
export const CUSTOMER_ORDER_PAID_FAIL = 'CUSTOMER_ORDER_PAID_FAIL';
export const CUSTOMER_ORDER_PAID_RESET = 'CUSTOMER_ORDER_PAID_RESET';

//DELETE CUSTOMER ORDER OPERATION(Delete)
// export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
// export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
// export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';