//CREATE PRODUCT OPERATION)(Create)
export const CUSTOMER_CREATE_REQUEST = 'CUSTOMER_CREATE_REQUEST';
export const CUSTOMER_CREATE_SUCCESS = 'CUSTOMER_CREATE_SUCCESS';
export const CUSTOMER_CREATE_FAIL = 'CUSTOMER_CREATE_FAIL';
export const CUSTOMER_CREATE_RESET = 'CUSTOMER_CREATE_RESET';   

//READ PRODUCT OPERATION(Read-LIST)
export const CUSTOMER_LIST_REQUEST = 'CUSTOMER_LIST_REQUEST';
export const CUSTOMER_LIST_SUCCESS = 'CUSTOMER_LIST_SUCCESS';
export const CUSTOMER_LIST_FAIL = 'CUSTOMER_LIST_FAIL';

//READ PRODUCT OPERATION(Read-DETAILS)
export const CUSTOMER_DETAILS_REQUEST = 'CUSTOMER_DETAILS_REQUEST';
export const CUSTOMER_DETAILS_SUCCESS = 'CUSTOMER_DETAILS_SUCCESS';
export const CUSTOMER_DETAILS_FAIL = 'CUSTOMER_DETAILS_FAIL';

//DELETE PRODUCT OPERATION(Update)
export const CUSTOMER_UPDATE_REQUEST = 'CUSTOMER_UPDATE_REQUEST';
export const CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS';
export const CUSTOMER_UPDATE_FAIL = 'CUSTOMER_UPDATE_FAIL';
export const CUSTOMER_UPDATE_RESET = 'CUSTOMER_UPDATE_RESET';

//DELETE PRODUCT OPERATION(Delete)
// export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
// export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
// export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';
