//CREATE PRODUCT OPERATION)(Create)
export const GAS_STOCK_CREATE_REQUEST = 'GAS_STOCK_CREATE_REQUEST';
export const GAS_STOCK_CREATE_SUCCESS = 'GAS_STOCK_CREATE_SUCCESS';
export const GAS_STOCK_CREATE_FAIL = 'GAS_STOCK_CREATE_FAIL';
export const GAS_STOCK_CREATE_RESET = 'GAS_STOCK_CREATE_RESET';   

//READ PRODUCT OPERATION(Read-LIST)
export const GAS_STOCK_LIST_REQUEST = 'GAS_STOCK_LIST_REQUEST';
export const GAS_STOCK_LIST_SUCCESS = 'GAS_STOCK_LIST_SUCCESS';
export const GAS_STOCK_LIST_FAIL = 'GAS_STOCK_LIST_FAIL';

//READ PRODUCT OPERATION(Read-DETAILS)
export const GAS_STOCK_DETAILS_REQUEST = 'GAS_STOCK_DETAILS_REQUEST';
export const GAS_STOCK_DETAILS_SUCCESS = 'GAS_STOCK_DETAILS_SUCCESS';
export const GAS_STOCK_DETAILS_FAIL = 'GAS_STOCK_DETAILS_FAIL';

//DELETE PRODUCT OPERATION(Update)
export const GAS_STOCK_UPDATE_REQUEST = 'GAS_STOCK_UPDATE_REQUEST';
export const GAS_STOCK_UPDATE_SUCCESS = 'GAS_STOCK_UPDATE_SUCCESS';
export const GAS_STOCK_UPDATE_FAIL = 'GAS_STOCK_UPDATE_FAIL';
export const GAS_STOCK_UPDATE_RESET = 'GAS_STOCK_UPDATE_RESET';

//DELETE PRODUCT OPERATION(Delete)
// export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
// export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
// export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';
