//READ PRODUCT OPERATION(Read-LIST)
export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL';
export const USER_CREATE_RESET = 'USER_CREATE_RESET';

//READ PRODUCT OPERATION(Read-LIST)
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

//READ PRODUCT OPERATION(Read-DETAILS)
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

//UPDATE OPERATION(Update)
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

//UPDATE OPERATION(Delete)
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

//UPDATE PROFILE
export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST';
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS';
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL';
export const USER_PROFILE_UPDATE_RESET = 'USER_PROFILE_UPDATE_RESET';

//UPDATE USER CREDENTIALS
export const USER_UPDATE_CREDNTIALS_REQUEST = 'USER_UPDATE_CREDNTIALS_REQUEST';
export const USER_UPDATE_CREDNTIALS_SUCCESS = 'USER_UPDATE_CREDNTIALS_SUCCESS';
export const USER_UPDATE_CREDNTIALS_FAIL = 'USER_UPDATE_CREDNTIALS_FAIL';
export const USER_UPDATE_CREDNTIALS_RESET =
  'USER_PROFILE_UPDATE_CREDNTIALS_RESET';   
